### ISSUE TITLE
How to change the font in the preview page

### ISSUE THREAD

**Issue by skysin** [gera2ld/markmap-vscode#23]
Is there any method to change the font in the preview page? such as fixed-width font?

Hacker tricks are also welcomed.

**Comment by gera2ld** [comment]
Since v0.0.13 there is a `Custom CSS` setting so you can override CSS there.

For example:

```css
.markmap-node {
  font-family: monospace;
}
```

Note that the custom CSS is added to `document.head` so you need to take care of the priorities.
